apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerd-test
  labels:
    app: containerd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerd-test
  template:
    metadata:
      labels:
        app: containerd-test
    spec:
      containers:
        - name: containerd-test
          image: yangk/containerd-test:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/run/dockershim.sock
              name: containerd
      volumes:
        - name: containerd
          hostPath:
            path: /var/run/dockershim.sock